version: '3'
services:
  jekyll:
    build: .
    volumes:
     - .:/srv
    ports:
     - "4000:4000"
    working_dir: /srv
    command: "bash -c \"bundle exec jekyll serve --drafts --host 0.0.0.0 --port 4000\""
