version: '3'
services:
  medium:
    image: latenightswift/medium
    env_file: .env
    build:
      context: ../../
      dockerfile: ./scripts/medium/Dockerfile
    volumes:
     - ../../:/home
    working_dir: /home/scripts/medium
